# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15S_wicZzVsEJ0oPEze82Be6eT-52rz48
"""

import streamlit as st
import pandas as pd
import firebase_admin
from firebase_admin import credentials, firestore
import json

# CONFIGURACIÓN DE PÁGINA

st.set_page_config(
    page_title="Movies Dashboard",
    page_icon="🎬",
    layout="wide"
)

# CONEXIÓN A FIRESTORE

def init_firebase():
    #Inicia conexión con Firebase usando los secrets de Streamlit
    if not firebase_admin._apps:
        cred_dict = dict(st.secrets["firebase"])
        cred = credentials.Certificate(cred_dict)
        firebase_admin.initialize_app(cred)
    return firestore.client()

# LECTURA DE FIRESTORE

@st.cache_data(ttl=300)
def obtener_todos_los_filmes():
    
    #Leer todos los registros de Firestore y convertirlos a DataFrame."
    db = init_firebase()
    coleccion = db.collection("movies")
    documentos = coleccion.get()

    registros = []
    for doc in documentos:
        data = doc.to_dict()
        data["doc_id"] = doc.id
        registros.append(data)

    df = pd.DataFrame(registros)
    return df

def insertar_filme(company, director, genre, name):
    #Función para agregar nuevos filmes en la colección
    db = init_firebase()
    coleccion = db.collection("movies")
    nuevo_filme = {
        "company": company,
        "director": director,
        "genre": genre,
        "name": name
    }
    coleccion.add(nuevo_filme)

def buscar_por_titulo(df, titulo):
    #Filtrar por título
    return df[df["name"].str.contains(titulo, case=False, na=False)]

def filtrar_por_director(df, director):
    #Filtrar por director
    return df[df["director"] == director]

# CARGAR DATASET AL ARRANQUE
df_base = obtener_todos_los_filmes()

# INTERFAZ PRINCIPAL
st.title("🎬 Dashboard Interactivo de Filmes")
st.markdown("Explora, busca y filtra filmes desde nuestra base de datos.")


# SIDEBAR
st.sidebar.title("⚙️ Opciones")

# 1. CHECKBOX: Ver todos los filmes
st.sidebar.markdown("---")
ver_todos = st.sidebar.checkbox("📋 Ver todos los filmes")

if ver_todos:
    st.header("📋 Todos los filmes")
    st.dataframe(df_base[["name", "director", "genre", "company"]], use_container_width=True)

# 2. BUSCAR POR TÍTULO
st.sidebar.markdown("---")
st.sidebar.subheader("🔍 Buscar por título")
titulo_busqueda = st.sidebar.text_input("Escribe el título (parcial o completo):")
btn_buscar = st.sidebar.button("Buscar título")

if btn_buscar:
    if titulo_busqueda.strip():
        resultados = buscar_por_titulo(df_base, titulo_busqueda.strip())
        st.header(f"🔍 Resultados para: \"{titulo_busqueda}\"")
        if len(resultados) > 0:
            st.success(f"Se encontraron {len(resultados)} filme(s).")
            st.dataframe(resultados[["name", "director", "genre", "company"]], use_container_width=True)
        else:
            st.warning("No se encontraron filmes con ese título.")
    else:
        st.warning("Por favor escribe un título para buscar.")

#3. FILTRAR POR DIRECTOR
st.sidebar.markdown("---")
st.sidebar.subheader("🎬 Filtrar por director")

directores = sorted(df_base["director"].dropna().unique().tolist())
director_seleccionado = st.sidebar.selectbox("Selecciona un director:", directores)
btn_filtrar = st.sidebar.button("Filtrar por director")

if btn_filtrar:
    filmes_director = filtrar_por_director(df_base, director_seleccionado)
    st.header(f"🎬 Filmes de: {director_seleccionado}")
    st.info(f"Total de filmes encontrados: {len(filmes_director)}")
    if len(filmes_director) > 0:
        st.dataframe(filmes_director[["name", "genre", "company"]], use_container_width=True)
    else:
        st.warning("No se encontraron filmes para este director.")

# 4. CAMPOS PARA INSERTAR NUEVO FILME
st.sidebar.markdown("---")
st.sidebar.subheader("➕ Agregar nuevo filme")

with st.sidebar.form(key="form_nuevo_filme"):
    nuevo_name = st.text_input("Título del filme *")
    nuevo_director = st.text_input("Director *")
    nuevo_genre = st.text_input("Género")
    nuevo_company = st.text_input("Compañía")
    btn_insertar = st.form_submit_button("Guardar filme")

if btn_insertar:
    if nuevo_name.strip() and nuevo_director.strip():
        try:
            insertar_filme(
                company=nuevo_company.strip(),
                director=nuevo_director.strip(),
                genre=nuevo_genre.strip(),
                name=nuevo_name.strip()
            )
            st.sidebar.success(f"✅ Filme \"{nuevo_name}\" insertado correctamente.")
            st.cache_data.clear()  # Limpiar caché para reflejar el nuevo dato
        except Exception as e:
            st.sidebar.error(f"❌ Error al insertar: {e}")
    else:
        st.sidebar.warning("El título y el director son obligatorios.")

# PIE DE PÁGINA
st.markdown("---")
st.caption(f"Total de filmes en la base de datos: {len(df_base)}")
